import AdmZip from "adm-zip";
import path from "path";
import { addDocument } from "./matters";

// Generous but bounded — this exists to stop a genuinely huge or malformed
// archive from tying up the request/disk indefinitely, not to police
// normal disclosure-package sizes.
const MAX_ENTRIES = 200;
const MAX_SINGLE_FILE_BYTES = 100 * 1024 * 1024;
const MAX_TOTAL_UNCOMPRESSED_BYTES = 500 * 1024 * 1024;

interface ZipEntryFile {
  fileName: string;
  data: Buffer;
}

// Flattens every real file in the zip (no folder structure — this app
// doesn't organize documents into folders) into a name+bytes pair.
// Directory entries, hidden/system files (.DS_Store, AppleDouble "._"
// resource forks left by macOS zip creation) are skipped. Entries are
// addressed only by their basename, and the actual on-disk storage path is
// always generated by addDocument() (UUID-prefixed, inside the matter's
// own upload directory) — so a malicious entryName like "../../etc/x"
// can't escape anywhere; it just becomes the literal filename "x".
export function extractZipEntries(buffer: Buffer): ZipEntryFile[] {
  const zip = new AdmZip(buffer);
  const entries = zip.getEntries().filter((entry) => !entry.isDirectory);

  const files: ZipEntryFile[] = [];
  let totalBytes = 0;
  for (const entry of entries) {
    const fileName = path.basename(entry.entryName);
    if (!fileName || fileName.startsWith(".")) continue;

    if (entry.header.size > MAX_SINGLE_FILE_BYTES) {
      throw new Error(
        `"${fileName}" is ${Math.round(entry.header.size / 1024 / 1024)} MB, over the ${MAX_SINGLE_FILE_BYTES / 1024 / 1024} MB limit for one file in a bulk import.`,
      );
    }
    totalBytes += entry.header.size;
    if (totalBytes > MAX_TOTAL_UNCOMPRESSED_BYTES) {
      throw new Error(
        `This zip's total uncompressed size exceeds the ${MAX_TOTAL_UNCOMPRESSED_BYTES / 1024 / 1024} MB limit for one bulk import.`,
      );
    }
    if (files.length >= MAX_ENTRIES) {
      throw new Error(`This zip contains more than ${MAX_ENTRIES} files — split it into smaller batches.`);
    }
    files.push({ fileName, data: entry.getData() });
  }
  return files;
}

export interface BulkImportResult {
  fileName: string;
  status: "uploaded" | "failed";
  documentId?: string;
  error?: string;
}

// Sequential on purpose — each upload already does real disk I/O plus a
// SQLite write, and the underlying database only supports one writer at a
// time; running these concurrently would just contend with itself. One
// file failing (duplicate detection isn't a failure — see addDocument —
// but e.g. a genuinely corrupt entry could throw) doesn't stop the rest.
export async function bulkImportZip(matterId: string, zipBuffer: Buffer): Promise<BulkImportResult[]> {
  const entries = extractZipEntries(zipBuffer);
  const results: BulkImportResult[] = [];
  for (const entry of entries) {
    try {
      const file = new File([new Uint8Array(entry.data)], entry.fileName);
      const document = await addDocument(matterId, file);
      results.push({ fileName: entry.fileName, status: "uploaded", documentId: document.id });
    } catch (err) {
      results.push({
        fileName: entry.fileName,
        status: "failed",
        error: err instanceof Error ? err.message : "Upload failed",
      });
    }
  }
  return results;
}
